function createfigure1(X1, Y1)
%CREATEFIGURE1(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 22-Aug-2017 19:50:21

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
box(axes1,'on');
hold(axes1,'on');

% Create plot
plot1 = plot(X1,Y1,'DisplayName','data1');

% Get xdata from plot
xdata1 = get(plot1, 'xdata');
% Get ydata from plot
ydata1 = get(plot1, 'ydata');
% Make sure data are column vectors
xdata1 = xdata1(:);
ydata1 = ydata1(:);


% Remove NaN values and warn
nanMask1 = isnan(xdata1(:)) | isnan(ydata1(:));
if any(nanMask1)
    warning('GeneratedCode:IgnoringNaNs', ...
        'Data points with NaN coordinates will be ignored.');
    xdata1(nanMask1) = [];
    ydata1(nanMask1) = [];
end

% Find x values for plotting the fit based on xlim
axesLimits1 = xlim(axes1);
xplot1 = linspace(axesLimits1(1), axesLimits1(2));

% Normalize xdata
normalizedXdata1 = (xdata1 - mean(xdata1))./(std(xdata1));
% Find normalized x values for plotting the fit
normalizedXplot1 = (xplot1 - mean(xdata1))./(std(xdata1));
% Find coefficients for shape-preserving interpolant
fitResults1 = pchip(normalizedXdata1, ydata1);
% Evaluate piecewise polynomial
yplot1 = ppval(fitResults1, normalizedXplot1);
% Plot the fit
fitLine1 = plot(xplot1,yplot1,'DisplayName','   shape-preserving',...
    'Tag','shape-preserving',...
    'Parent',axes1,...
    'Color',[0.85 0.325 0.098]);

% Set new line in proper position
setLineOrder(axes1, fitLine1, plot1);

% Create legend
legend(axes1,'show');

%-------------------------------------------------------------------------%
function setLineOrder(axesh1, newLine1, associatedLine1)
%SETLINEORDER(AXESH1,NEWLINE1,ASSOCIATEDLINE1)
%  Set line order
%  AXESH1:  axes
%  NEWLINE1:  new line
%  ASSOCIATEDLINE1:  associated line

% Get the axes children
hChildren = get(axesh1,'Children');
% Remove the new line
hChildren(hChildren==newLine1) = [];
% Get the index to the associatedLine
lineIndex = find(hChildren==associatedLine1);
% Reorder lines so the new line appears with associated data
hNewChildren = [hChildren(1:lineIndex-1);newLine1;hChildren(lineIndex:end)];
% Set the children:
set(axesh1,'Children',hNewChildren);

